# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ro

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  # Domain Classifier for detecting the microworld
  - name: components.domain_classifier.DomainClassifier
    epochs: 100
    entity_recognition: False
  # Classifier for detecting the microworld-specific intent and entities
  - name: components.microworld_classifier.MicroworldClassifier
    epochs: 100
    microworlds:
      generic:
        epochs: 100
      university_guide:
        epochs: 100
      mem_assistant:
        epochs: 100
  - name: components.syntactic_parser.SyntacticParser
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.2
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: utter_unknown
