version: '3.8'

services:
  # React web UI for interacting with the bot
  #  web:
  #    image: registry.gitlab.com/gabrielboroghina/pepper-conv-agent/pepper-web
  #  environment:
  #    RASA_SERVER_HOST: http://
  #    ports:
  #      - 80:80

  # Conversational agent server
  rasa-server:
    image: registry.gitlab.com/gabrielboroghina/pepper-conv-agent/rasa-server
    container_name: rasa-server
    environment:
      RASA_ACTIONS_API_HOST: rasa-actions
      RASA_ACTIONS_API_PORT: 5055
    ports:
      - 80:80
    #    domainname: "pepperconvagent"
    command: "rasa run -p 80 --enable-api --endpoints endpoints.compose.yml --cors *"
    depends_on:
      - actions

  # RASA actions HTTP server
  rasa-actions:
    image: registry.gitlab.com/gabrielboroghina/pepper-conv-agent/rasa-actions
    container_name: rasa-actions
    environment:
      KB_API_URL: "http://graphdb:7200/repositories/pepper"
      KB_BASE_URI: "http://www.readerbench.com/pepper"
    depends_on:
      - graphdb

  # Knowledge base
  graphdb:
    image: registry.gitlab.com/gabrielboroghina/pepper-conv-agent/graphdb
    container_name: graphdb
    volumes:
      - graphdb:/opt/graphdb-instance/

volumes:
  graphdb:
    driver: azure_file
    driver_opts:
      share_name: graphdb
      storage_account_name: gabiboro