version: '3.8'

services:
  # React web UI for interacting with the bot
  web:
    image: pepper-web
    ports:
      - "3000:3000"
    stdin_open: true

  # Conversational agent server
  rasa-server:
    image: pepper-rasa
    environment:
      RASA_ACTIONS_API_HOST: rasa-actions
      RASA_ACTIONS_API_PORT: 5003
    ports:
      - "5005:5005"
    command: "rasa run --enable-api --endpoints endpoints.yml --cors * -p 5005"
    depends_on:
      - rasa-actions

  # RASA actions HTTP server
  rasa-actions:
    image: registry.gitlab.com/gabrielboroghina/pepper-conv-agent/rasa-actions
    environment:
      GRAPHDB_API_HOST: graphdb
    command: "rasa run actions -p 5003"
    ports:
      - "5003:5003"
    depends_on:
      - graphdb

  # Knowledge base
  graphdb:
    image: registry.gitlab.com/gabrielboroghina/pepper-conv-agent/graphdb
    ports:
      - "80:80" # Export GraphDB port to access the GraphDB Workbench
    volumes:
      - graphdb:/opt/graphdb-instance/

volumes:
  graphdb:
