version: '3.8'

services:
  # React web UI for interacting with the bot
  web:
    image: pepper-web
    ports:
      - 3000:3000
    stdin_open: true

  # Conversational agent server
  rasa-server:
    image: pepper-rasa
    environment:
      RASA_ACTIONS_API_HOST: actions
      RASA_ACTIONS_API_PORT: 5055
    ports:
      - 5005:5005
    command: "rasa run --enable-api --endpoints endpoints.prod.yml --cors *"
    depends_on:
      - actions

  # RASA actions HTTP server
  actions:
    image: pepper-actions
    environment:
      GRAPHDB_API_HOST: graphdb:7200
    depends_on:
      - graphdb

  # Knowledge base
  graphdb:
    image: graphdb
    ports:
      - 7200:7200 # Export GraphDB port to access the GraphDB Workbench
    volumes:
      - graphdb:/opt/graphdb-instance/

volumes:
  graphdb:
