deps = [
    "-",
    "prep",
    "ROOT",
    "cine",
    "care",
    "ce fel de",
    "ce",
    "pe cine",
    "unde",
    "când",
    "cât timp",
    "la cât timp",
    "cât de des",
    "cum este",
    "care este",
    "al cui",
    "cât",
    "cui",
]

allowed_deps = ["unde", "când", "cât timp", "care este"]
# allowed_deps = ["unde", "când", "cât timp", "cine", "care este"]

precomputed_deps = {
    "Bună!": ['-', '-'],
    "Hei": ['-'],
    "hey": ['-'],
    "salut": ['-'],
    "bună": ['-'],
    "salutare": ['-'],
    "hello": ['-'],
    "bună ziua": ['-', '-'],
    "Salut": ['-'],
    "hi": ['-'],
    "hei!": ['-', '-'],
    "Îți multumesc mult pentru ajutor": ['-', '-', '-', '-', '-'],
    "Mulțumesc de ajutor": ['-', '-', '-'],
    "Mi-ai fost de mare ajutor": ['-', '-', '-', '-', '-', '-', '-'],
    "Mersi!": ['-', '-'],
    "Mulțu": ['-'],
    "Mulțumesc!": ['-', '-'],
    "super": ['-'],
    "Tare": ['-'],
    "Cool": ['-'],
    "Nice": ['-'],
    "mersi mult": ['-', '-'],
    "merci": ['-'],
    "bye": ['-'],
    "pa": ['-'],
    "paa": ['-'],
    "paaa": ['-'],
    "pa pa": ['-', '-'],
    "papa": ['-'],
    "gata": ['-'],
    "o zi frumoasă": ['-', '-', '-'],
    "da": ['-'],
    "daa": ['-'],
    "da da": ['-', '-'],
    "dada": ['-'],
    "dap": ['-'],
    "sigur": ['-'],
    "ok": ['-'],
    "yep": ['-'],
    "yes": ['-'],
    "Ce e o minge?": ['-', '-', '-', '-', '-'],
    "Ce e un calculator?": ['-', '-', '-', '-', '-'],
    "Cine e Bill Gates?": ['-', '-', '-', '-', '-'],
    "Ce știi să faci?": ['-', '-', '-', '-', '-'],
    "Cu ce mă poți ajuta?": ['-', '-', '-', '-', '-', '-'],
    "Ce pot să te întreb?": ['-', '-', '-', '-', '-', '-'],
    "Ce știi?": ['-', '-', '-'],
    "La ce fel de întrebări poți răspunde?": ['-', '-', '-', '-', '-', '-', '-', '-'],
    "Spune-mi ce te pot întreba": ['-', '-', '-', '-', '-', '-', '-'],
    "Ce informații pot afla?": ['-', '-', '-', '-', '-'],
    "Help": ['-'],
    "Ajutor": ['-'],
    "Care sunt tipurile de întrebări la care răspunzi?": ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Care este rolul tău?": ['-', '-', '-', '-', '-'],
    "care sunt abilitățile tale?": ['-', '-', '-', '-', '-'],
    "capabilități": ['-'],
    "abilități": ['-'],
    "ce cunoștințe ai": ['-', '-', '-'],
    "am nevoie de ajutor": ['-', '-', '-', '-'],
    "Vreau exemple de întrebări": ['-', '-', '-', '-'],
    "Dă-mi exemplu de ce te pot întreba": ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "vreau exemple": ['-', '-'],
    "care sunt exemplele?": ['-', '-', '-', '-'],
    "exemple de replici": ['-', '-', '-'],
    "vreau să ajung la casa presei libere": ['-', '-', '-', '-', 'unde', '-', '-'],
    "as dori sa ajung la piata unirii": ['-', '-', '-', '-', '-', 'unde', '-'],
    "cum ajung repede in otopeni?": ['unde', '-', '-', '-', 'unde', '-'],
    "poti sa-mi zici cum sa ajung in Pantelimon?": ['-', '-', '-', '-', '-', '-', '-', '-', '-', 'unde', '-'],
    "vreau să merg la dristor": ['-', '-', '-', '-', 'unde'],
    "aș dori să mă duc la facultate": ['-', '-', '-', '-', '-', '-', 'unde'],
    "arata-mi directii spre universitate": ['-', '-', '-', '-', '-', 'unde'],
    "vreau direcții către palatul parlamentului": ['-', '-', '-', 'unde', '-'],
    "cum fac să merg in Herăstrău?": ['unde', '-', '-', '-', '-', 'unde', '-'],
    "care sunt rutele să ajung la mausoleu?": ['-', '-', '-', '-', '-', '-', 'unde', '-'],
    "cum pot să merg până la parcul tineretului?": ['-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "cum merg spre bragadiru?": ['-', '-', '-', 'unde', '-'],
    "arată-mi rute către stația de metrou Orizont": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "zi-mi cum ajung pe lacul morii": ['-', '-', '-', '-', '-', '-', 'unde', '-'],
    "Arata-mi te rog cum merg la Gara de Nord": ['-', '-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "Vreau sa vad cum mă duc la Apusului": ['-', '-', '-', '-', '-', '-', '-', 'unde'],
    "Aș vrea să merg în parcul sticlariei": ['-', '-', '-', '-', '-', 'unde', '-'],
    "ce mijloace de transport merg spre promenada": ['-', '-', '-', '-', '-', '-', 'unde'],
    "ce mijloace pot să iau până la farmacia tei?": ['-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "cum pot ajunge rapid la laserul de la Măgurele": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "vreau să merg în sectorul 5": ['-', '-', '-', '-', 'unde', '-'],
    "trebuie să ajung pe strada lalelelor": ['-', '-', '-', '-', 'unde', '-'],
    "dă-mi transport către arena națională": ['-', '-', '-', '-', '-', 'unde', '-'],
    "Vreau să reții ceva": ['-', '-', '-', '-'],
    "Poți să reții ceva, te rog?": ['-', '-', '-', '-', '-', '-', '-', '-'],
    "Memorează": ['-'],
    "Memorează ceva": ['-', '-'],
    "Reține ceva": ['-', '-'],
    "Ține minte": ['-', '-'],
    "Memo": ['-'],
    "reține": ['-'],
    "aș dori să stochez ceva": ['-', '-', '-', '-', '-'],
    "aș vrea să ții ceva în memorie": ['-', '-', '-', '-', '-', '-', 'unde'],
    "reține ce îți zic": ['-', '-', '-', '-'],
    "cartea e pe masă": ['cine', '-', '-', 'unde'],
    "Cardul de debit este în portofelul vechi": ['cine', '-', '-', '-', '-', 'unde', '-'],
    "buletinul meu se află în rucsac": ['cine', '-', '-', '-', '-', 'unde'],
    "biblioteca se află la etajul 5": ['cine', '-', '-', '-', 'unde', '-'],
    "service-ul gsm este pe strada Ecaterina Teodoroiu numărul 12": ['cine', '-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-'],
    "Am pus foile cu tema la mate pe dulapul din sufragerie": ['-', '-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "Alex stă în căminul P5": ['cine', '-', '-', 'unde', '-'],
    "Maria Popescu locuiește pe Bulevardul Timișoara numărul 5": ['cine', '-', '-', '-', 'unde', '-', '-', '-'],
    "Daniela stă la blocul 23": ['cine', '-', '-', 'unde', '-'],
    "eu stau la adresa str. Ec. Teod. nr. 17": ['cine', '-', '-', 'unde', '-', '-', '-', '-', '-', '-', '-'],
    "Bonurile de transport sunt în plicul de pe raft": ['cine', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "cardul de memorie e sub cutia telefonului": ['cine', '-', '-', '-', '-', 'unde', '-'],
    "tastatura mea este în depozit": ['cine', '-', '-', '-', 'unde'],
    "profesorul se află în camera vecină": ['cine', '-', '-', '-', 'unde', '-'],
    "am lăsat lădița cu cartofi în pivniță": ['-', '-', '-', '-', '-', '-', 'unde'],
    "mi-am pus casca de înot în dulapul cu tricouri": ['-', '-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "geaca de iarnă este în șifonierul de acasă": ['cine', '-', '-', '-', '-', 'unde', '-', '-'],
    "lămpile solare sunt de la bricostore": ['cine', '-', '-', '-', '-', 'unde'],
    "perechea de adidași albi este de la intersport din Afi": ['cine', '-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "Alin Dumitru stă în Militari Residence": ['cine', '-', '-', '-', 'unde', '-'],
    "am lăsat suportul de brad la țară în garaj": ['-', '-', '-', '-', '-', '-', 'unde', '-', 'unde'],
    "pachetul de creioane colorate este pe polița de pe perete": ['cine', '-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "mi-am așezat prosoapele pe suport": ['-', '-', '-', '-', '-', '-', 'unde'],
    "am cumpărat florile de la mireille": ['-', '-', '-', '-', '-', 'unde'],
    "am luat veioza de la București": ['-', '-', '-', '-', '-', 'unde'],
    "sandalele sunt de la magazinul benvenutti": ['cine', '-', '-', '-', 'unde', '-'],
    "trandafirii sunt de la Nicu": ['cine', '-', '-', '-', 'unde'],
    "chitara mea este de la Andrei": ['cine', '-', '-', '-', '-', 'unde'],
    "am mers cu mașina până la Iași": ['-', '-', '-', '-', '-', '-', 'unde'],
    "telefonul lui Jan este pe noptieră": ['cine', '-', '-', '-', '-', 'unde'],
    "tricoul meu de alergat e în șifonier pe hol": ['cine', '-', '-', '-', '-', '-', 'unde', '-', 'unde'],
    "trusa de machiaj a Anisiei este în geamantanul verde": ['cine', '-', '-', '-', '-', '-', '-', 'unde', '-'],
    "ganterele lui Horia sunt sub canapea": ['cine', '-', '-', '-', '-', 'unde'],
    "bormașina cu percuție a lui Vlad e la Timișoara": ['cine', '-', '-', '-', '-', '-', '-', '-', 'unde'],
    "pungile acestea sunt de la mall": ['cine', '-', '-', '-', '-', 'unde'],
    "Bob se află pe stația spațială": ['cine', '-', '-', '-', 'unde', '-'],
    "Clara a venit de pe muntele Olimp": ['cine', '-', '-', '-', '-', 'unde', '-'],
    "Rodica se întoarce de la festivalul Untold": ['cine', '-', '-', '-', '-', 'unde', '-'],
    "Unde se află ochelarii": ['unde', '-', '-', 'cine'],
    "Unde e buletinul?": ['unde', '-', '-', 'cine'],
    "știi unde am pus cheile": ['-', 'unde', '-', '-', '-'],
    "poți să-mi zici unde este încârcătorul de telefon": ['-', '-', '-', '-', '-', 'unde', '-', 'cine', '-', '-'],
    "zi-mi unde am pus ochelarii de înot": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "unde am lăsat ceasul?": ['unde', '-', '-', '-', '-'],
    "pe unde e sticla de ulei": ['-', 'unde', '-', 'cine', '-', '-'],
    "pe unde mi-am pus pantofii negri": ['-', 'unde', '-', '-', '-', '-', '-', '-'],
    "de unde am cumpărat uscătorul de păr": ['-', 'unde', '-', '-', '-', '-', '-'],
    "de unde au venit cartofii în Europa": ['-', 'unde', '-', '-', 'cine', '-', 'unde'],
    "de unde pleacă trenul IR1892": ['-', 'unde', '-', 'cine', '-'],
    "până unde a alergat aseară Marius?": ['-', 'unde', '-', '-', 'când', 'cine', '-'],
    "până unde au ajuns radiațiile de la Cernobâl": ['-', 'unde', '-', '-', 'cine', '-', '-', '-'],
    "de unde am luat draperiile din sufragerie?": ['-', 'unde', '-', '-', '-', '-', '-', '-'],
    "spune-mi te rog unde a pus Alina dosarul cu actele de la serviciu": ['-', '-', '-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "ai putea să îmi zici unde era casa lui Teo?": ['-', '-', '-', '-', '-', 'unde', '-', 'cine', '-', '-', '-'],
    "mailul lui Alex este următorul": ['cine', '-', '-', '-', 'care este'],
    "valoarea constantei pi este următoarea": ['cine', '-', '-', '-', 'care este'],
    "colegii care au luat 10 la ML sunt următorii:": ['cine', '-', '-', '-', '-', '-', '-', '-', 'care este', '-'],
    "materiile opționale din anul 1 sunt următoarele": ['cine', '-', '-', '-', '-', '-', '-'],
    "tehnologiile folosite de aplicație sunt următoarele": ['cine', '-', '-', 'unde', '-', 'care este'],
    "codul de acces este ăsta": ['cine', '-', '-', '-', 'care este'],
    "numărul de la casă al Mariei e acesta": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "dimensiunile portbagajului meu de la mașină sunt acestea": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "adresa mea de la București e aceasta": ['cine', '-', '-', '-', '-', '-', 'care este'],
    "versiunile de Windows 10 sunt acestea": ['cine', '-', '-', '-', '-', 'care este'],
    "lunile pe care am decontat abonamentul sunt cele care urmează": ['cine', '-', 'unde', '-', '-', '-', '-', 'care este', '-', '-'],
    "ecuația fluxului electromagnetic e cea care urmează": ['cine', '-', '-', '-', 'care este', '-', '-'],
    "colegii mei de liceu erau cei ce urmează": ['cine', '-', '-', '-', '-', 'care este', '-', '-'],
    "dioptriile mele de la ochelari erau ultima dată cele ce urmează": ['cine', '-', '-', '-', '-', '-', '-', 'când', 'care este', '-', '-'],
    "programul de la notarul de la Universitate este acesta:": ['cine', '-', '-', '-', '-', '-', '-', '-', 'care este', '-'],
    "programul de lucru al lui Cristian e ăsta": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "explicatia indicatorului albastru este asta": ['cine', '-', '-', '-', 'care este'],
    "Mailul lui Alex Marin este alex@marin.com": ['cine', '-', '-', '-', '-', 'care este'],
    "Adresa Elenei este strada Zorilor numărul 9": ['cine', '-', '-', 'care este', '-', '-', '-'],
    "Numărul de telefon al lui Dan e 123456789": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "numărul blocului fratelui Mihaelei e 10": ['cine', '-', '-', '-', '-', 'care este'],
    "anul nașterii lui Ștefan cel Mare a fost 1433": ['cine', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "numele meu este Gabriel": ['cine', '-', '-', 'care este'],
    "adresa de la serviciu este Bulevardul Unirii nr. 0": ['cine', '-', '-', '-', '-', 'care este', '-', '-', '-'],
    "numele asistentului de programare paralelă e Paul Walker": ['cine', '-', '-', '-', '-', '-', 'care este', '-'],
    "suprafața apartamentului de la București este de 58mp": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "prețul canapelei a fost de 1300 de lei": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "codul de activare al sistemului de operare e APCHF6798HJ67GI90": ['cine', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "sala laboratorului de PP este EG321": ['cine', '-', '-', '-', '-', 'care este'],
    "username-ul meu de github este gabrielboroghina": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "seria mea de la buletin este GG2020": ['cine', '-', '-', '-', '-', '-', 'care este'],
    "codul PIN de la cardul meu de sănătate este 0000": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "placa mea video este NVidia GeForce GTX950m": ['cine', '-', '-', '-', 'care este', '-', '-', '-'],
    "telefonul Karinei este 243243": ['cine', '-', '-', 'care este'],
    "limbajul de programare folosit de Thales este C++": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "tensiunea nominală de alimentare a pompei este 120V": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "data de expirare a suplimentelor alimentare din cămară este 30-05-2023": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "Care e mailul lui Mihai?": ['-', '-', 'cine', '-', '-', '-'],
    "care este numele de utilizator de github al laborantului de EIM": ['-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-', '-'],
    "poți să-mi spui care era prețul abonamentului la sală": ['-', '-', '-', '-', '-', '-', '-', 'cine', '-', '-', '-'],
    "zi-mi care a fost câștigătorul concursului Eestec Olympics de anul trecut": ['-', '-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "care era denumirea bazei de date de la proiect?": ['-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-'],
    "care sunt tipurile de rețele neurale": ['-', '-', 'cine', '-', '-', '-'],
    "care este valoarea de adevăr a propoziției": ['-', '-', 'cine', '-', '-', '-', '-'],
    "care e adresa colegului meu?": ['-', '-', 'cine', '-', '-', '-'],
    "care e frecvența procesorului meu": ['-', '-', 'cine', '-', '-'],
    "care e numărul lui Radu": ['-', '-', 'cine', '-', '-'],
    "care e limita de viteză în localitate": ['-', '-', 'cine', '-', '-', '-', '-'],
    "care e punctul de topire al aluminiului": ['-', '-', 'cine', '-', '-', '-', '-'],
    "care e data de naștere a lui Mihai Popa": ['-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "care este mărimea mea la adidași": ['-', '-', 'cine', '-', '-', '-'],
    "care este temperatura medie în Monaco în iunie": ['-', '-', 'cine', '-', '-', '-', '-', '-'],
    "care este diferența de vârstă între mine și Vlad": ['-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "zi-mi și mie care era adresa de căsuță poștală a Karinei Preda": ['-', '-', '-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "care sunt datele cardului meu revolut": ['-', '-', 'cine', '-', '-', '-'],
    "care este telefonul de la frizerie": ['-', '-', 'cine', '-', '-', '-'],
    "care e dobânda de la creditul pentru casă?": ['-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "care sunt ministerele cu probleme": ['-', '-', 'cine', '-', '-'],
    "care este tipografia centrală": ['-', '-', 'cine', '-'],
    "spune-mi care este seria mea de la buletin": ['-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-'],
    "vreau să știu care e numele de familie al lui Sebi": ['-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-', '-'],
    "aș vrea să îmi zici te rog care e termenul limită al temei de la algebră": ['-', '-', '-', '-', '-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "ce floare s-a uscat": ['-', 'cine', '-', '-', '-', '-'],
    "ce hackathon va avea loc săptămâna viitoare": ['-', 'cine', '-', '-', '-', 'când', '-'],
    "ce windows am acum pe calculator": ['-', 'cine', '-', '-', '-', '-'],
    "ce examene vor fi date în iunie?": ['-', 'cine', '-', '-', '-', '-', 'când', '-'],
    "ce temperatură a fost în iulie anul trecut": ['-', 'cine', '-', '-', '-', 'când', 'când', '-'],
    "ce culoare au ochii Andreei": ['-', 'cine', '-', '-', '-'],
    "ce mail am folosit la serviciu": ['-', 'cine', '-', '-', '-', 'unde'],
    "la ce apartament locuiește verișorul meu": ['-', '-', 'unde', '-', 'cine', '-'],
    "la ce sală se află microscopul electronic": ['-', '-', 'unde', '-', '-', 'cine', '-'],
    "la ce număr de telefon se dau informații despre situația actuală": ['-', '-', 'unde', '-', '-', '-', '-', '-', '-', 'unde', '-'],
    "la care salon este internat bunicul lui": ['-', '-', 'unde', '-', '-', 'cine', '-'],
    "la care cod poștal a fost trimis pachetul": ['-', '-', 'unde', '-', '-', '-', '-', 'cine'],
    "la care hotel s-au cazat Mihai și Alex ieri": ['-', '-', 'unde', '-', '-', '-', '-', 'cine', '-', 'cine', 'când'],
    "ce fel de imprimantă am acasă": ['-', '-', '-', '-', '-', '-'],
    "ce fel de baterie folosește ceasul de mână": ['-', '-', '-', '-', '-', 'cine', '-', '-'],
    "ce fel de procesor are telefonul meu": ['-', '-', '-', '-', '-', 'cine', '-'],
    "în care dulap am pus dosarul": ['-', '-', 'unde', '-', '-', '-'],
    "în care cameră am lăsat încărcătorul de telefon": ['-', '-', 'unde', '-', '-', '-', '-', '-'],
    "în care săptămână e examenul de învățare automată": ['-', '-', 'când', '-', 'cine', '-', '-', '-'],
    "de la care prieten e cadoul acesta": ['-', '-', '-', 'unde', '-', 'cine', '-'],
    "de la care magazin mi-am luat cablul de date?": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-', '-', '-'],
    "pentru ce test am învățat acum 2 zile": ['-', '-', '-', '-', '-', '-', '-', 'când'],
    "pe care masă am pus ieri periuța de dinți?": ['-', '-', 'unde', '-', '-', 'când', '-', '-', '-', '-'],
    "pe care poziție este mașina în parcare": ['-', '-', 'unde', '-', 'cine', '-', '-'],
    "de pe care cont am plătit factura de curent acum 3 zile": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-', '-', 'când'],
    "pe ce viteză am setat aerul condiționat": ['-', '-', '-', '-', '-', '-', '-'],
    "pe ce loc am ieșit la olimpiada de info din clasa a 12-a": ['-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-'],
    "care aparat de făcut sandwichuri e la reducere": ['-', 'cine', '-', '-', '-', '-', '-', '-'],
    "ce fel de uscător de păr folosește Alice": ['-', '-', '-', '-', '-', '-', '-', '-'],
    "care clasificare e corectă": ['-', 'cine', '-', '-'],
    "care emisferă este": ['-', '-', '-'],
    "care elicopter": ['-', '-'],
    "care autoturism este cel mai prietenos cu mediul": ['-', 'cine', '-', '-', '-', '-', '-', '-'],
    "la ce sprânceană e problema": ['-', '-', '-', '-', 'cine'],
    "la ce fel de neurooftalmologie trebuie să meargă?": ['-', '-', '-', '-', 'unde', '-', '-', '-', '-'],
    "pentru care deversare au fost amedați": ['-', '-', '-', '-', '-', '-'],
    "ce fel de pocănit se auzea ieri": ['-', '-', '-', '-', '-', '-', 'când'],
    "concursul va fi pe 12 ianuarie": ['cine', '-', '-', '-', 'când', '-'],
    "îmi expiră permisul de conducere pe 25 februarie 2023": ['-', '-', 'cine', '-', '-', '-', 'când', '-', '-'],
    "plecarea în Franța este pe 5 martie": ['cine', '-', '-', '-', '-', 'când', '-'],
    "abonamentul STB îmi expiră pe 23 aprilie": ['cine', '-', '-', '-', '-', 'când', '-'],
    "Viorel e născut pe 16 mai 1998": ['cine', '-', '-', '-', 'când', '-', '-'],
    "Vacanța de vară începe pe 30 iunie": ['cine', '-', '-', '-', '-', 'când', '-'],
    "Pe 3 iulie se termină sesiunea de licență": ['-', 'când', '-', '-', '-', 'cine', '-', '-'],
    "ziua Daianei este în august": ['cine', '-', '-', '-', 'când'],
    "în septembrie începe școala": ['-', 'când', '-', 'cine'],
    "din octombrie apare un nou film la cinema": ['-', 'când', '-', '-', '-', '-', '-', 'unde'],
    "până în noiembrie trebuie să termin task-ul": ['-', '-', 'când', '-', '-', '-', '-', '-', '-'],
    "noile autobuze au apărut în decembrie": ['-', 'cine', '-', '-', '-', 'când'],
    "luni am fost la alergat": ['când', '-', '-', '-', 'unde'],
    "am mers la bazinul de înot marți": ['-', '-', '-', 'unde', '-', '-', 'când'],
    "garanția de la frigider se termină marțea viitoare": ['cine', '-', '-', '-', '-', '-', 'când', '-'],
    "coletul cu jacheta va ajunge miercuri": ['cine', '-', '-', '-', '-', 'când'],
    "testul de curs la rețele neurale a fost joi": ['cine', '-', '-', '-', '-', '-', '-', '-', 'când'],
    "vineri încep promoțiile de black friday": ['când', '-', 'cine', '-', '-', '-'],
    "până sâmbătă e interzis accesul în mall": ['-', 'când', '-', '-', 'cine', '-', 'unde'],
    "Jack a fost la biserică duminică": ['cine', '-', '-', '-', 'unde', 'când'],
    "azi am fost în parcul Titan": ['când', '-', '-', '-', 'unde', '-'],
    "Mâine vine Mihai pe la mine": ['când', '-', 'cine', '-', '-', 'unde'],
    "poimâine merg la mall": ['când', '-', '-', 'unde'],
    "olimpiada internațională de geografie va începe răspoimâine": ['cine', '-', '-', '-', '-', '-', 'când'],
    "de ieri s-a făcut cald afară": ['-', 'când', '-', '-', '-', '-', '-', 'unde'],
    "am terminat proiecul la programare web alaltăieri": ['-', '-', '-', '-', '-', '-', 'când'],
    "procesorul Intel i7 rulează o instrucțiune în 0.3 nanosecunde": ['cine', '-', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "execuția interogării în baza de date a durat 500 de milisecunde": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "sesiunea din browser a expirat acum 10 secunde": ['cine', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "prezentarea proiectului durează 45 de minute": ['cine', '-', '-', '-', '-', 'cât timp'],
    "am de prezentat temele peste o oră": ['-', '-', '-', '-', '-', '-', 'cât timp'],
    "am mâncat acum 2 ore": ['-', '-', '-', '-', 'cât timp'],
    "peste 3 sferturi de oră o să ajungă Ina": ['-', '-', 'cât timp', '-', '-', '-', '-', '-', 'cine'],
    "întâlnirea cu managerul este peste o jumătate de oră": ['cine', '-', '-', '-', '-', '-', 'cât timp', '-', '-'],
    "peste 2 zile începe examenul de bacalaureat": ['-', '-', 'cât timp', '-', 'cine', '-', '-'],
    "Maria pleacă în concediu peste 5 săptămâni": ['cine', '-', '-', 'unde', '-', 'cât timp', '-'],
    "săptămâna viitoare încep cursurile de înot": ['când', '-', '-', 'cine', '-', '-'],
    "conferința de bioinformatică a fost acum o lună": ['cine', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "peste 2 ani termină Nicoleta masterul": ['-', '-', 'cât timp', '-', 'cine', '-'],
    "buletinul îmi expiră peste 3 ani": ['cine', '-', '-', '-', '-', 'cât timp'],
    "mi-am făcut pașaportul acum un an": ['-', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "bătălia de la Mărășești a avut loc în anul 1917": ['cine', '-', '-', '-', '-', '-', '-', '-', 'când', '-'],
    "acum 5 decenii nu existau calculatoare": ['-', '-', 'cât timp', '-', '-', '-'],
    "în secolul 19 s-a dezvoltat Imperiul lui Napoleon": ['-', 'când', '-', '-', '-', '-', '-', 'cine', '-', '-'],
    "luna viitoare vine Florin din Spania": ['când', '-', '-', 'cine', '-', '-'],
    "meciul dintre Franța și Spania va fi în weekend": ['cine', '-', '-', '-', '-', '-', '-', '-', 'când'],
    "la anul se deschide mall-ul din Slatina": ['-', 'când', '-', '-', 'cine', '-', '-', '-', '-'],
    "mi-am făcut analize primăvara trecută": ['-', '-', '-', '-', '-', 'când', '-'],
    "restricțiile de circulație se încheie la vară": ['cine', '-', '-', '-', '-', '-', 'când'],
    "toamna viitoare încep masterul": ['când', '-', '-', '-'],
    "Darius și-a schimbat domiciliul iarna trecută": ['cine', '-', '-', '-', '-', '-', 'când', '-'],
    "curierul o să vină diseară": ['cine', '-', '-', '-', 'când'],
    "aseară am făcut cartofi prăjiți": ['când', '-', '-', '-', '-'],
    "tonerul de la imprimantă s-a terminat alaltăseară": ['cine', '-', '-', '-', '-', '-', '-', '-', 'când'],
    "bunica lui Alice va face cozonaci mâine dimineață": ['cine', '-', '-', '-', '-', '-', 'când', 'când'],
    "ieri seara a fost foarte frig afară": ['când', 'când', '-', '-', '-', '-', 'unde'],
    "de dimineață trebuie să hrănesc animalele": ['-', 'când', '-', '-', '-', '-'],
    "am fost la cumpărături după amiază": ['-', '-', '-', 'unde', '-', 'când'],
    "la răsărit a început să cânte cocoșul din grădină": ['-', 'când', '-', '-', '-', '-', '-', '-', '-'],
    "evaluarea națională a ținut 2 ore și 45 de minute": ['-', '-', '-', '-', '-', 'cât timp', '-', '-', '-', 'cât timp'],
    "Jacob locuiește în Bremen de un an și 4 luni": ['cine', '-', '-', 'unde', '-', '-', 'cât timp', '-', '-', 'cât timp'],
    "trebuie să iau antibioticul o dată la 6 ore": ['-', '-', '-', '-', '-', 'când', '-', '-', 'cât timp'],
    "bazinul de apă se umple o dată la 30 de minute": ['cine', '-', '-', '-', '-', '-', 'când', '-', '-', '-', 'cât timp'],
    "Marc ia vitaminele de 2 ori pe zi": ['cine', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "eu merg la sală de 3 ori pe săptămână": ['cine', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "mgazinul se aprovizionează în fiecare săptămână": ['cine', '-', '-', '-', '-', '-'],
    "în fiecare an apare un nou telefon Samsung Galaxy": ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "serviciul funcționează de luni până vineri": ['cine', '-', '-', 'când', '-', 'când'],
    "de joi va putea ajunge în Germania cu trenul": ['-', 'când', '-', '-', '-', '-', 'unde', '-', '-'],
    "până pe 24 iunie trebuie să trimit lucrarea de diplomă": ['-', '-', 'când', '-', '-', '-', '-', '-', '-', '-'],
    "festivalul de muzică ușoară și dans va fi de pe 1 septembrie pe 10 octombrie": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'când', '-', '-', 'când', '-'],
    "de pe 23 până pe 27 am fost în concediu": ['-', '-', 'când', '-', '-', 'când', '-', '-', '-', 'unde'],
    "între 3 și 7 ianuarie am fost la conferință în Toronto": ['-', 'când', '-', 'când', '-', '-', '-', '-', 'unde', '-', 'unde'],
    "la polul nord este noapte timp de 6 luni": ['-', 'unde', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "Andra și-a ales rochia de bal după 2 săptămâni": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'cât timp'],
    "de la ora 18 se oprește curentul electric": ['-', '-', 'când', '-', '-', '-', 'cine', '-'],
    "când vor avea loc alegerile locale din 2020": ['când', '-', '-', '-', 'cine', '-', '-', '-'],
    "Când am avut ultimul examen anul trecut?": ['când', '-', '-', '-', '-', 'când', '-', '-'],
    "zi-mi când am fost la sală?": ['-', '-', '-', 'când', '-', '-', '-', 'unde', '-'],
    "De când începe vacanța": ['-', 'când', '-', 'cine'],
    "Până când trebuie trimisă tema": ['-', 'când', '-', '-', 'cine'],
    "până când a durat al 2-lea război mondial?": ['-', 'când', '-', '-', '-', '-', '-', 'cine', '-'],
    "până când trebuie rezolvată problema la vlsi": ['-', 'când', '-', '-', 'cine', '-', '-'],
    "cât timp a durat prezentarea temei": ['-', 'cât timp', '-', '-', 'cine', '-'],
    "peste cât timp se termină starea de urgență?": ['-', '-', 'cât timp', '-', '-', '-', 'cine', '-', '-'],
    "peste cât timp începe sesiunea de examene": ['-', '-', 'cât timp', '-', 'cine', '-', '-'],
    "când trebuie să merg la control oftalmologic": ['când', '-', '-', '-', '-', 'unde', '-'],
    "când trebuie să iau pastilele de stomac": ['când', '-', '-', '-', '-', '-', '-'],
    "cât de des se actualizează sistemul de operare?": ['-', '-', 'când', '-', '-', '-', 'cine', '-', '-'],
    "cât de des trebuie să ud florile din fața casei": ['-', '-', 'când', '-', '-', '-', '-', '-', '-', '-'],
    "în ce perioadă se va ține concursul de fizică de la Bacău": ['-', '-', 'când', '-', '-', '-', 'cine', '-', '-', '-', '-', '-'],
    "în ce perioadă vor avea loc preselecțiile pentru balul bobocilor": ['-', '-', 'când', '-', '-', '-', 'cine', '-', '-', '-'],
    "în care perioadă a fost cel mai frig afară?": ['-', '-', 'când', '-', '-', '-', '-', '-', '-', 'unde'],
    "în ce interval e deschis magazinul Kaufland de la Giurgiu?": ['-', '-', 'când', '-', '-', '-', 'cine', '-', '-', '-', '-'],
    "în ce interval de timp a avut loc atacul": ['-', '-', 'când', '-', '-', '-', '-', '-', 'cine'],
    "de când până când se vor închide magazinele": ['-', 'când', '-', 'când', '-', '-', '-', 'cine'],
    "de când până când pot citi indexul de energie electrică": ['-', 'când', '-', 'când', '-', '-', '-', '-', '-', '-'],
    "Cine stă în căminul P16?": ['cine', '-', '-', 'unde', '-', '-'],
    "Spune-mi te rog cine a inventat becul": ['-', '-', '-', '-', '-', 'cine', '-', '-', '-'],
    "cine a câștigat locul 1 la olimpiada națională de matematică din 2016": ['cine', '-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "cine m-a tuns ultima dată?": ['cine', '-', '-', '-', '-', '-', '-', 'când'],
    "de la cine a cumpărat mihaela cireșele": ['-', '-', 'unde', '-', '-', 'cine', '-'],
    "de la cine a apărut problema": ['-', '-', 'unde', '-', '-', 'cine'],
    "cine a fost primul om pe lună?": ['cine', '-', '-', '-', '-', '-', '-', '-'],
    "cine a venit ieri la cursul de astronomie": ['cine', '-', '-', 'când', '-', 'unde', '-', '-'],
    "zi-mi cine a propus problemele de la concursul InfoOlt 2016": ['-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Unde are biroul Mihai Dascalu?": ['unde', '-', '-', '-', 'cine', '-'],
    "Unde este Răzvan Deaconescu?": ['unde', '-', 'cine', '-', '-'],
    "Unde il pot gasi pe Florin Pop?": ['unde', '-', '-', '-', '-', '-', '-', '-'],
    "Care e biroul lui Marius Leordeanu": ['cine', '-', '-', '-', '-', '-'],
    "Spune-mi te rog unde se află biroul lui Mihnea Moisescu": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-'],
    "Știi unde îl pot găsi pe profesorul Dan Tudose?": ['-', 'unde', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Oare unde este domnul profesor Traian Rebedea?": ['-', 'unde', '-', 'cine', '-', '-', '-', '-'],
    "Zi-mi și mie unde are Mariana Mocanu biroul în facultate": ['-', '-', '-', '-', '-', 'unde', '-', 'cine', '-', '-', '-', '-'],
    "Unde îl găsesc pe asistentul Emilian Rădoi?": ['unde', '-', '-', '-', '-', '-', '-', '-'],
    "Spune care e biroul domnului Gologan": ['-', 'cine', '-', '-', '-', '-'],
    "Unde stă de obicei doamna profesoară Adina Paunescu": ['unde', '-', '-', '-', 'cine', '-', '-', '-'],
    "Vreau să găsesc pe Marius Popescu": ['-', '-', '-', '-', '-', '-'],
    "Aș dori să ajung la laborantul Cosmin Dragomir": ['-', '-', '-', '-', '-', 'unde', '-', '-'],
    "Unde merg să îl găsesc pe asistentul Alexandru Negrescu?": ['unde', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Unde e biroul lui Radu Ciobanu?": ['unde', '-', 'cine', '-', '-', '-', '-'],
    "Afișează-mi harta etajului corespunzător sălii PR 303!": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Ajută-mă să găsesc sala PR 706!": ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Ajută-mă să găsesc sala PR 103b!": ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Am nevoie de ajutor să găsesc drumul către sala PR 303!": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Arată-mi calea către sala PR 701!": ['-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Arată-mi harta cu sala PR 002 reprezentată.": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Care este direcția către sala PR 605?": ['cine', '-', '-', '-', '-', '-', '-', '-'],
    "Care este drumul către sala PR 706?": ['cine', '-', '-', '-', '-', '-', '-', '-'],
    "Care este drumul spre sala PR 103a?": ['cine', '-', '-', '-', '-', '-', '-', '-'],
    "Condu-mă la sala PR 305!": ['-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Cum pot ajunge la sala PR 603?": ['-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Există vreo hartă pentru a vizualiza localizarea sălii PR 403?": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Explică-mi cum ajung la sala PR 403!": ['-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Indică-mi drumul către sala PR 003!": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "La ce etaj se află sala PR 604?": ['-', '-', '-', '-', '-', 'cine', '-', '-', '-'],
    "Mă conduci până la sala PR 103a?": ['-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Mă poți ghida către sala PR 608?": ['-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Mă poți îndrepta către sala PR 002?": ['-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Mă poți îndruma către sala PR 408?": ['-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Pe unde se află sala PR 604?": ['-', 'unde', '-', '-', 'cine', '-', '-', '-'],
    "Pe unde să o iau ca să ajung la sala PR 702?": ['-', 'unde', '-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Poti să mă conduci la sala PR 701, te rog?": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-'],
    "Poți să îmi indici drumul către sala PR 608?": ['-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Spune-mi unde găsesc sala PR 001!": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "Unde e sala PR 305?": ['unde', '-', 'cine', '-', '-', '-'],
    "Unde este localizată sala PR 708?": ['unde', '-', '-', 'cine', '-', '-', '-'],
    "Unde găsesc sala PR 103b?": ['unde', '-', '-', '-', '-', '-'],
    "Unde pot găsi sala PR 001?": ['unde', '-', '-', '-', '-', '-', '-'],
    "Unde se află sala PR 606?": ['unde', '-', '-', 'cine', '-', '-', '-'],
    "Vreau să văd harta cu sala PR 301 reprezentată.": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Zi-mi unde găsesc sala PR 003!": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "Îmi poți arăta calea către sala PR 702, te rog?": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Îmi poți arăta o hartă cu sala PR 106 reprezentată.": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Îmi poți explica unde se află sala PR 302, te rog?": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "În ce direcție se găsește sala PR 601?": ['-', '-', '-', '-', '-', 'cine', '-', '-', '-'],
    "În ce loc se află sala PR 605?": ['-', '-', 'unde', '-', '-', 'cine', '-', '-', '-'],
    "În ce sens se află sala PR 307?": ['-', '-', 'unde', '-', '-', 'cine', '-', '-', '-'],
    "Încotro să o iau către sala PR 203?": ['unde', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Știi unde se află sala PR 606?": ['-', 'unde', '-', '-', 'cine', '-', '-', '-'],
    "Unde e AN 02": ['unde', '-', 'cine', '-'],
    "Cum ajung în EG413?": ['-', '-', '-', 'unde', '-'],
    "Ajută-mă să găsesc sala unde se ține Programare Orientata pe Obiecte!": ['-', '-', '-', '-', '-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-'],
    "Arată-mi sala în care se desfășoară Elemente de Electronica Analogica!": ['-', '-', '-', '-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-'],
    "Mă poți ajuta să găsesc unde are loc Logica?": ['-', '-', '-', '-', '-', '-', '-', '-', '-', 'cine'],
    "Spune-mi, te rog, în ce sală pot participa la Cultura si Civilizatie?": ['-', '-', '-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-', '-'],
    "Unde are loc Instrumente Informatice?": ['unde', '-', '-', 'cine', '-', '-'],
    "Unde se desfășoară Paradigme de Programare?": ['unde', '-', '-', 'cine', '-', '-', '-'],
    "Unde se predă Proiectarea Algoritmilor?": ['unde', '-', 'cine', '-', '-', '-'],
    "Unde trebuie să mă duc pentru a participa la Istoria Religiilor?": ['unde', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Unde va avea loc Filosofie Cognitivista?": ['unde', '-', '-', '-', 'cine', '-', '-'],
    "Îmi poți spune, te rog, unde se va ține Retele Locale?": ['-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-', 'cine', '-', '-'],
    "În ce loc se ține Ingineria Calculatoarelor?": ['-', '-', 'unde', '-', '-', 'cine', '-', '-'],
    "În ce sală are loc Mecanica?": ['-', '-', 'unde', '-', '-', 'cine', '-'],
    "Știi unde se desfășoară Proiectare Logica?": ['-', 'unde', '-', '-', 'cine', '-', '-'],
    "Știi unde se va ține Algoritmi Paraleli si Distribuiti?": ['-', 'unde', '-', '-', '-', 'cine', '-', '-', '-', '-'],
    "Unde se ține Metode Numerice?": ['unde', '-', '-', 'cine', '-', '-'],
    "Unde se ține laboratorul pentru grupa 311CC?": ['unde', '-', '-', 'cine', '-', '-', '-', '-'],
    "Unde se ține cursul pentru seria CB?": ['unde', '-', '-', 'cine', '-', '-', '-', '-'],
    "Zi-mi te rog unde are loc curs pentru seria CA": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-'],
    "Vreau să știu unde se desfășoară seminarul grupei 222AC": ['-', '-', '-', 'unde', '-', '-', 'cine', '-', '-'],
    "Unde se ține cursul de Electronica Digitala pentru seria CC?": ['unde', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-'],
    "Unde se ține seminarul de Teoria Sistemelor pentru grupa 315CB?": ['unde', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-'],
    "Unde se ține seminar de Engleza pentru grupa 321CC?": ['unde', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Aș vrea să știu unde e seminarul de Mate pentru grupa 142BB": ['-', '-', '-', '-', 'unde', '-', 'cine', '-', '-', '-', '-', '-'],
    "Zi-mi unde va fi cursul seriei S1 de analiză matematică": ['-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-', '-', '-'],
    "Proiectare Logică": ['-', '-'],
    "materia de Fizică": ['-', '-', '-'],
    "mă interesa materia Calculatoare Numerice 1": ['-', '-', '-', '-', '-', '-'],
    "curs": ['-'],
    "seminar": ['-'],
    "laborator": ['-'],
    "laboratorul de la Proiectare cu Microprocesoare": ['-', '-', '-', '-', '-', '-'],
    "cursul de Programare Orientata pe Obiecte": ['-', '-', '-', '-', '-', '-'],
    "seminarul de la Chimie aplicată": ['-', '-', '-', '-', '-'],
    "Semnale și sisteme, seria AB": ['-', '-', '-', '-', '-', '-'],
    "Metode Numerice de la seria CA": ['-', '-', '-', '-', '-', '-'],
    "grupa 331CB materia Sisteme de operare": ['-', '-', '-', '-', '-', '-'],
    "seminar de Algebră și Geometrie": ['-', '-', '-', '-', '-'],
    "3CC": ['-'],
    "in grupa 333CC": ['-', '-', '-'],
    "grupa 512AA": ['-', '-'],
    "sunt în grupa 232": ['-', '-', 'unde', '-'],
    "sunt de la seria AC": ['-', '-', '-', 'unde', '-'],
    "de la 412C1": ['-', '-', '-'],
    "seria CTI": ['-', '-'],
    "eu fac parte din grupa 311CD": ['cine', '-', '-', '-', 'unde', '-'],
    "pentru seria CB": ['-', '-', '-'],
    # =====================================================================================================================================================================
    "Buna": ['-'],
    "o zi buna": ['-', '-', '-'],
    "super!": ['-', '-'],
    "mulțumesc mult": ['-', '-'],
    "mersi de informație": ['-', '-', '-'],
    "Cum poti sa ma ajuti": ['-', '-', '-', '-', '-'],
    "ce te pot intreba": ['-', '-', '-', '-'],
    "vreau ajutor": ['-', '-'],
    "mă poți ajuta cu ceva?": ['-', '-', '-', '-', '-', '-'],
    "la ce te pricepi": ['-', '-', '-', '-'],
    "care sunt lucrurile pe care știi să le faci?": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "ce știi?": ['cine', '-', '-'],
    "ce știi tu?": ['-', '-', '-', '-'],
    "Niște exemple de întrebări te rog": ['-', '-', '-', '-', '-', '-'],
    "vreau ceva exemple": ['-', '-', '-'],
    "arata-mi niște exemple de întrebări": ['-', '-', '-', '-', '-', '-', '-'],
    "Cum aș putea să ajung până la Universitate?": ['-', '-', '-', '-', '-', '-', '-', '-', 'unde'],
    "Dă-mi trasee către Voluntari": ['-', '-', '-', '-', '-', 'unde'],
    "vreau rutele de transport spre spitalul floreasca": ['-', '-', '-', '-', '-', 'unde', '-'],
    "as vrea sa merg la dedeman": ['-', '-', '-', '-', '-', 'unde'],
    "vreau sa ma duc la Lujerului": ['-', '-', '-', '-', '-', 'unde'],
    "ce iau ca să ajung în Băneasa": ['-', '-', '-', '-', '-', '-', 'unde'],
    "Reține te rog": ['-', '-', '-'],
    "memo te rog": ['-', '-', '-'],
    "ține minte ceva": ['-', '-', '-'],
    "atlasul de geografie se află pe raftul cu dicționarul": ['cine', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "am pus bateria externă în rucsacul albastru": ['-', '-', '-', '-', '-', 'unde', '-'],
    "cheia franceză e pe balcon": ['cine', '-', '-', '-', 'unde'],
    "cartela mea SIM veche este sub cutia telefonului": ['cine', '-', '-', '-', '-', '-', 'unde', '-'],
    "am lăsat geanta în dulapul numărul 4": ['-', '-', '-', '-', 'unde', '-', '-'],
    "Victor stă pe Aleea Romancierilor numărul 12": ['cine', '-', '-', 'unde', '-', '-', '-'],
    "eu stau la blocul nr. 8": ['cine', '-', '-', 'unde', '-', '-'],
    "am lăsat mașina la service-ul auto din Crângași": ['-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "pliculețele de praf de copt sunt în cutiuța din primul sertar": ['cine', '-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "am așezat etuiul de la ochelari peste teancul de reviste din hol": ['-', '-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-', '-'],
    "am luat ornamentele de la dedeman": ['-', '-', '-', '-', '-', 'unde'],
    "roșiile din lădiță sunt de la țară": ['cine', '-', '-', '-', '-', '-', 'unde'],
    "gladiolele sunt de la florăria din oraș": ['cine', '-', '-', '-', 'unde', '-', '-'],
    "cartea de matematică a Mariei este pe biroul meu": ['cine', '-', '-', '-', '-', '-', '-', 'unde', '-'],
    "insigna de la facultate este pe rucsacul negru": ['cine', '-', '-', '-', '-', '-', 'unde', '-'],
    "geanta de voiaj este de la Samsonite": ['cine', '-', '-', '-', '-', '-', 'unde'],
    "cadoul este de la colegul meu de apartament": ['cine', '-', '-', '-', 'unde', '-', '-', '-'],
    "am luat ochelarii de la mall": ['-', '-', '-', '-', '-', 'unde'],
    "unde am pus caietul de matematică 1?": ['unde', '-', '-', '-', '-', '-', '-', '-'],
    "știi unde sunt burghiele mici": ['-', 'unde', '-', '-', '-'],
    "pe unde am lăsat pompa de bicicletă": ['-', 'unde', '-', '-', '-', '-', '-'],
    "unde locuiește Claudia Ionescu": ['unde', '-', 'cine', '-'],
    "de unde este brelocul meu de la chei?": ['-', 'unde', '-', 'cine', '-', '-', '-', '-', '-'],
    "unde se află bazinul de înot Dinamo": ['unde', '-', '-', 'cine', '-', '-', '-'],
    "unde mi-am aruncat sculele de construcții": ['unde', '-', '-', '-', '-', '-', '-', '-'],
    "de unde mi-am luat cravata cea grena": ['-', 'unde', '-', '-', '-', '-', '-', '-', '-'],
    "zi-mi unde am lăsat certificatul meu de naștere": ['-', 'unde', '-', '-', '-', '-', '-', '-', '-', '-'],
    "unde este setul de baterii pentru mouse?": ['unde', '-', 'cine', '-', '-', '-', '-', '-'],
    "codul meu IBAN este următorul": ['cine', '-', '-', '-', 'care este'],
    "linkul de la concursul ACM de anul trecut e următorul": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "studenții care s-au înscris la masterul de securitate sunt următorii": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "numerele de telefon ale Georgianei sunt acestea": ['cine', '-', '-', '-', '-', '-', 'care este'],
    "emailul lui Ionuț este acesta": ['cine', '-', '-', '-', 'care este'],
    "membrii lotului de informatică din 2016 sunt cei care urmează": ['cine', '-', '-', '-', '-', '-', '-', 'care este', '-', '-'],
    "codul meu numeric personal este cel ce urmează": ['cine', '-', '-', '-', '-', 'care este', '-', '-'],
    "teorema lui Pitagora este asta": ['cine', '-', '-', '-', 'care este'],
    "modelul SSD-ului meu e ăsta": ['cine', '-', '-', '-', '-', '-', 'care este'],
    "hotelul la care ne-am cazat anul trecut la mare e acesta:": ['cine', '-', '-', '-', '-', '-', '-', 'când', '-', '-', 'unde', '-', 'care este', '-'],
    "telefonul Dianei este 0745789654": ['cine', '-', '-', 'care este'],
    "prețul ceasului meu Atlantic a fost 500 de lei": ['cine', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "numărul de la mașină al Elenei este B 07 ELN": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "codul de identificare al cardului meu de de acces la birou este 57627": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 'care este'],
    "numele profesoarei mele de biologie din liceu este Mariana Mihai": ['cine', '-', '-', '-', '-', '-', '-', '-', 'care este', '-'],
    "mărimea la tricou a lui Teo este L": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "materiile la care am luat 9 sunt M1 și M2": ['cine', '-', '-', '-', '-', '-', '-', 'care este', '-', '-'],
    "rank-ul universității Politehnica este 800": ['cine', '-', '-', '-', '-', '-', 'care este'],
    "tipul de baterii de la tastatură este AAA": ['cine', '-', '-', '-', '-', '-', '-', 'care este'],
    "modelul tastaturii mele este logitech mx keys": ['cine', '-', '-', '-', 'care este', '-', '-'],
    "ziua de naștere a Grațielei este pe 12 mai 1995": ['cine', '-', '-', '-', '-', '-', '-', 'care este', '-', '-'],
    "care este telefonul Dianei": ['cine', '-', '-', '-'],
    "care este prețul ceasului meu Atlantic": ['cine', '-', '-', '-', '-', '-'],
    "care este numărul de la mașină al Elenei": ['cine', '-', '-', '-', '-', '-', '-', '-'],
    "zi-mi care e codul PIN de la cardul meu de sănătate": ['-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "care e numele profesoarei mele de biologie din liceu": ['cine', '-', '-', '-', '-', '-', '-', '-', '-'],
    "care sunt cele mai bune întrerupătoare": ['cine', '-', '-', '-', '-', '-'],
    "care era emailul asistentului de la APP?": ['cine', '-', '-', '-', '-', '-', '-', '-'],
    "care a fost durata domniei lui Cezar": ['cine', '-', '-', '-', '-', '-', '-'],
    "zi-mi care e codul de pe spatele telefonului": ['-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "care e vărsta de pensionare la bărbați": ['cine', '-', '-', '-', '-', '-', '-'],
    "care era modelul tastaturii mele?": ['cine', '-', '-', '-', '-', '-'],
    "care este înălțimea vârfului Everest?": ['cine', '-', '-', '-', '-', '-'],
    "la ce apartament stă Alex Marin?": ['-', '-', '-', '-', 'cine', '-', '-'],
    "ce fel de bec am pus la bucătărie": ['-', '-', '-', '-', '-', '-', '-', 'unde'],
    "în care dulap am lăsat plasa?": ['-', '-', 'unde', '-', '-', '-', '-'],
    "de la ce magazin am luat tortul de la ziua mea": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-', '-'],
    "care colegi au luat 10 la chimie": ['-', 'cine', '-', '-', '-', '-', '-'],
    "care copil a rupt scaunul de la școală": ['-', 'cine', '-', '-', '-', '-', '-', '-'],
    "ce profesor a prezentat la conferință": ['-', 'cine', '-', '-', '-', 'unde'],
    "în ce zi e născut unchiul meu?": ['-', '-', 'când', '-', '-', 'cine', '-', '-'],
    "care dinamometru e afară": ['-', 'cine', '-', 'unde'],
    "ce floare este de la expo flora?": ['-', 'cine', '-', '-', '-', 'unde', '-', '-'],
    "care persoane suferă de diabet": ['-', 'cine', '-', '-', '-'],
    "care bomboane sunt pentru ziua ei": ['-', 'cine', '-', '-', '-', '-'],
    "ce os a înghițit acel băiat": ['-', 'cine', '-', '-', '-', '-'],
    "care bomboane sunt de la auchan": ['-', 'cine', '-', '-', '-', 'unde'],
    "mâine se termină perioada de rodaj a mașinii": ['când', '-', '-', 'cine', '-', '-', '-', '-'],
    "examenul la ML este peste 4 zile": ['cine', '-', '-', '-', '-', '-', 'cât timp'],
    "testul practic de EIM o să fie săptămâna viitoare": ['cine', '-', '-', '-', '-', '-', '-', 'când', '-'],
    "peste o zi expiră prăjiturile": ['-', '-', 'cât timp', '-', 'cine'],
    "ieri m-am tuns": ['când', '-', '-', '-', '-'],
    "aniversarea prieteniei cu Andreea e pe 30 aprilie": ['cine', '-', '-', '-', '-', '-', 'când', '-'],
    "am trimis rezolvările la gazeta matematică miercurea trecută": ['-', '-', '-', '-', 'unde', '-', 'când', '-'],
    "vineri apare revista historia": ['când', '-', 'cine', '-'],
    "virusul a apărut acum 3 luni": ['cine', '-', '-', '-', '-', 'cât timp'],
    "peste 123 de secunde trecem în noul an": ['-', '-', '-', 'cât timp', '-', '-', '-', '-'],
    "hackathonul s-a organizat weekend-ul trecut": ['cine', '-', '-', '-', '-', 'când', '-', '-', '-'],
    "la primăvară e gata blocul": ['-', 'când', '-', '-', 'cine'],
    "voi pleca in Monaco peste 3 ore": ['-', '-', '-', 'unde', '-', '-', 'cât timp'],
    "am udat floarea roșie aseară": ['-', '-', '-', '-', 'când'],
    "mâine la prânz o să tund gazonul": ['când', '-', 'când', '-', '-', '-', '-'],
    "alaltăieri după amiază a plouat cu piatră la Botoșani": ['când', '-', 'când', '-', '-', '-', '-', '-', 'unde'],
    "de 3 ori pe oră trebuie să verific starea panoului de control": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "o dată la 4 ani se schimbă primarii": ['-', '-', '-', '-', '-', '-', '-', 'cine'],
    "Dan vine acasă din Germania în fiecare vară": ['cine', '-', 'unde', '-', 'unde', '-', '-', 'cât de des'],
    "copierea fișierelor de pe un disk pe altul a durat 4 minute": ['cine', '-', '-', '-', '-', 'unde', '-', '-', '-', '-', '-', 'cât timp'],
    "am alergat timp de o oră și jumătate": ['-', '-', '-', '-', '-', 'cât timp', '-', '-'],
    "acum 3 ore și 15 minute președintele John Kennedy a ținut un discurs": ['-', '-', 'cât timp', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "când începe vacanța de iarnă": ['când', '-', 'cine', '-', '-'],
    "când am fost la mare anul trecut": ['când', '-', '-', '-', 'unde', 'când', '-'],
    "de când s-a deschis McDonalds din Slatina": ['-', 'când', '-', '-', '-', '-', 'cine', '-', '-'],
    "cât timp a durat bătălia de la Oituz": ['-', 'cât timp', '-', '-', 'cine', '-', '-', '-'],
    "când am fost plecat în Germania": ['când', '-', '-', '-', '-', 'unde'],
    "până când va dura festivalul de muzică folk?": ['-', 'când', '-', '-', 'cine', '-', '-', '-', '-'],
    "de cât timp s-a deschis fabrica de mașini din Pitești": ['-', '-', 'cât timp', '-', '-', '-', '-', 'cine', '-', '-', '-', '-'],
    "de cât timp era însurat Ghiță": ['-', '-', 'cât timp', '-', '-', 'cine'],
    "pentru cât timp o să fie plecat Mihai": ['-', '-', 'cât timp', '-', '-', '-', '-', 'cine'],
    "în cât timp am urcat pe vârful Omu?": ['-', '-', 'cât timp', '-', '-', '-', 'unde', '-', '-'],
    "peste cât timp începe sesiunea de comunicări științifice?": ['-', '-', 'cât timp', '-', 'cine', '-', '-', '-', '-'],
    "cât de des vin cei de la amenajări stradale să îngrijească plantele": ['-', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-'],
    "de când până când se va lucra la reamenajarea clădirii?": ['-', 'când', '-', 'când', '-', '-', '-', '-', '-', '-', '-'],
    "în ce perioadă se vor da biletele gratis la operă": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "în ce interval o să se ia apa la apartament": ['-', '-', 'când', '-', '-', '-', '-', '-', '-', 'unde'],
    "peste cât timp o să se aprindă focul de tabără": ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "cine a inventat motorul cu reacție": ['cine', '-', '-', '-', '-', '-'],
    "cine a fost la ziua mea acum 3 ani": ['cine', '-', '-', '-', 'când', '-', '-', '-', '-'],
    "cine m-a ajutat la proiectul de la anatomie?": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "cine mi-a reparat bateria de la chiuveta de la baie?": ['cine', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "spune-mi te rog cine a luat 10 la arhitectura sistemelor de calcul": ['-', '-', '-', '-', '-', 'cine', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "Spune-mi te rog unde are biroul Ciprian Truică": ['-', '-', '-', '-', '-', 'unde', '-', '-', 'cine', '-'],
    "Zi-mi unde îl găsesc pe domnul Emil Slușanschi": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-'],
    "Unde are profesoara Irina Mocanu biroul din facultate?": ['unde', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "Știi cumva care e biroul profesorului Ciprian Dobre?": ['-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "Vreau să știu unde ar putea fi domnul Rughiniș": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-'],
    "Arată-mi cum ajung în EC105": ['-', '-', '-', '-', '-', '-', 'unde'],
    "Cum pot să găsesc sala PR 204": ['-', '-', '-', '-', '-', '-', '-'],
    "Poți să mă ghidezi te rog către PR001?": ['-', '-', '-', '-', '-', '-', '-', 'unde', '-'],
    "Mă poți ajuta să ajung la sala EG 203?": ['-', '-', '-', '-', '-', '-', 'unde', '-', '-', '-'],
    "pe unde pot merge către sala PR 306": ['-', 'unde', '-', '-', '-', 'unde', '-', '-'],
    "caut sala EC104, știi cumva unde este?": ['-', '-', '-', '-', '-', '-', 'unde', '-', '-'],
    "Zi-mi unde se ține Analiza Algoritmilor!": ['-', '-', '-', 'unde', '-', '-', 'cine', '-', '-'],
    "Spune-mi unde are loc Calculatoare Numerice te rog": ['-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-'],
    "Știi unde va fi fizica?": ['-', 'unde', '-', '-', 'cine', '-'],
    "Aș vrea să aflu unde o să fie predată teoria sistemelor": ['-', '-', '-', '-', '-', '-', '-', '-', '-', 'cine', '-'],
    "în ce sală va avea loc semnale și sisteme?": ['-', '-', 'unde', '-', '-', '-', 'cine', '-', '-', '-'],
    "Unde se ține seminarul de la grupa 313CC?": ['unde', '-', '-', 'cine', '-', '-', '-', '-', '-'],
    "Poți să îmi spui unde are loc laboratorul pentru seria CA?": ['-', '-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-', '-'],
    "Spune-mi te rog unde va avea loc cursul seriei AA": ['-', '-', '-', '-', '-', 'unde', '-', '-', '-', 'cine', '-', '-'],
    "Arată-mi unde se desfășoară laborator pentru grupa 12": ['-', '-', '-', 'unde', '-', '-', '-', '-', '-', '-'],
    "Aș vrea să aflu unde va fi seminarul de la grupa 123A": ['-', '-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-', '-'],
    "Unde se ține curs de Programare Avansată în Java pentru seria AC?": ['unde', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Aș vrea să îmi zici unde are loc laboratorul de programare orientată pe obiecte al grupei 333CD": ['-', '-', '-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-', '-'],
    "Vreau să aflu unde o să fie seminarul de fizică de la grupa 31C": ['-', '-', '-', 'unde', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-'],
    "Poți să îmi spui unde se ține cursul de la seria CA de mecanică?": ['-', '-', '-', '-', 'unde', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-'],
    "Unde o să fie predat laboratorul de la grupa 15 de structuri de date?": ['unde', '-', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-', '-', '-'],
    "sunt de la grupa 333CD": ['-', '-', '-', 'unde', '-'],
    "pentru seria CA": ['-', '-', '-'],
    "511AC": ['-'],
    "seminarul": ['-'],
    "cursul de Proiectare logică": ['-', '-', '-', '-'],
    "la materia de Arhitectura sistemelor de calcul": ['-', '-', '-', '-', '-', '-', '-'],
    "mersi": ['-'],
    "numarul de telefon al mariei este asta": ['cine', '-', '-', '-', '-', '-', '-'],
    "Unde va avea loc seminarul de ingineria programelor": ['unde', '-', '-', '-', 'cine', '-', '-', '-'],
    "unde o sa fie cursul de ingineria programelor de la seria CA": ['unde', '-', '-', '-', 'cine', '-', '-', '-', '-', '-', '-', '-'],
}